service: cognito-serverless
provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          integration: lambda
          authorizer:
            name: authorizer
            arn: your-user-pool-arn
